/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Venta;
import Punto_De_Venta.Usuario;
import Punto_De_Venta.Productos;
import Punto_De_Venta.Clientes;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
/**
 *
 * @author uziel
 */
public class principal extends javax.swing.JFrame {
    
    public ArrayList<Usuario> lusu= new ArrayList<Usuario>();
    public ArrayList<Productos> pdproductos= new ArrayList<Productos>();
    public ArrayList<Clientes> clclientes= new ArrayList<Clientes>();
    public String rol;
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    
    public void enviarUsuarios(ArrayList<Usuario> lu, String nu, String ro)
    {
      this.lusu = lu;
      jlusuario.setText(nu);
      this.rol= ro;
      
      
      if(rol.compareTo("Administrador")!=0){
          usuario.setVisible(false);
          C_Usuario.setVisible(false);
          c_cliente.setVisible(false);
          C_Producto.setVisible(false);
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        producto = new javax.swing.JButton();
        C_Producto = new javax.swing.JButton();
        usuario = new javax.swing.JButton();
        C_Usuario = new javax.swing.JButton();
        venta = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cliente = new javax.swing.JButton();
        c_cliente = new javax.swing.JButton();
        jlusuario = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("                                           Proyecto de textiles");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        producto.setBackground(new java.awt.Color(255, 255, 255));
        producto.setForeground(new java.awt.Color(255, 51, 51));
        producto.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\producto image.jpg")); // NOI18N
        producto.setText("Productos");
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });

        C_Producto.setForeground(new java.awt.Color(255, 0, 51));
        C_Producto.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\producto crud.jpg")); // NOI18N
        C_Producto.setText("CRUD Productos");
        C_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ProductoActionPerformed(evt);
            }
        });

        usuario.setForeground(new java.awt.Color(0, 102, 255));
        usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\usuario.jpg")); // NOI18N
        usuario.setText("Usuarios");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        C_Usuario.setForeground(new java.awt.Color(51, 51, 255));
        C_Usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\usuario crud.jpg")); // NOI18N
        C_Usuario.setText("CRUD Usuarios");
        C_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_UsuarioActionPerformed(evt);
            }
        });

        venta.setForeground(new java.awt.Color(51, 204, 0));
        venta.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\ventas.jpg")); // NOI18N
        venta.setText("Venta");
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });

        salir.setForeground(new java.awt.Color(153, 0, 0));
        salir.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\salir.jpg")); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        cliente.setForeground(new java.awt.Color(255, 153, 51));
        cliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\clientes.jpg")); // NOI18N
        cliente.setText("Clientes");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        c_cliente.setForeground(new java.awt.Color(255, 102, 0));
        c_cliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\uziel\\Downloads\\clientes crud.jpg")); // NOI18N
        c_cliente.setText("CRUD Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(C_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlusuario))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto)
                    .addComponent(C_Producto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(C_Usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente)
                    .addComponent(c_cliente))
                .addGap(18, 18, 18)
                .addComponent(venta)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
        CatalogoProductos cp = new CatalogoProductos(this,true);
        cp.iniciar(this);
        cp.setVisible(true);
        
    }//GEN-LAST:event_productoActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        CatalogoUsuarios ctu = new CatalogoUsuarios(this,true);
        ctu.iniciar(this);
        ctu.setVisible(true);
    }//GEN-LAST:event_usuarioActionPerformed

    private void C_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_UsuarioActionPerformed
        // TODO add your handling code here:
        usuarios us= new usuarios(this, true);
        us.iniciar(this);
        us.setVisible(true);
    }//GEN-LAST:event_C_UsuarioActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        CatalogoClientes cc = new CatalogoClientes(this,true);
        cc.iniciar(this);
        cc.setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private void C_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ProductoActionPerformed
        // TODO add your handling code here:
        productos pd= new productos(this, true);
        pd.iniciar(this);
        pd.setVisible(true);
    }//GEN-LAST:event_C_ProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    public void serializarClientes()
    {
       FileOutputStream archivo;
       ObjectOutputStream salida;
       try{
       
           archivo= new FileOutputStream("clientes.dat");
           salida= new ObjectOutputStream(archivo);
           if(salida!=null)
               salida.writeObject(clclientes);
           
           salida.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
    
    public void serializarProductos()
    {
       FileOutputStream archivo;
       ObjectOutputStream salida;
       try{
       
           archivo= new FileOutputStream("productos.dat");
           salida= new ObjectOutputStream(archivo);
           if(salida!=null)
               salida.writeObject(pdproductos);
           
           salida.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
    
    public void serializarUsuarios()
    {
       FileOutputStream archivo;
       ObjectOutputStream salida;
       try{
       
           archivo= new FileOutputStream("usuarios.dat");
           salida= new ObjectOutputStream(archivo);
           if(salida!=null)
               salida.writeObject(lusu);
           
           salida.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
    
    public void deserializarClientes()
    {
       FileInputStream archivo;
       ObjectInputStream entrada;
       try{
       
           archivo= new FileInputStream("clientes.dat");
           entrada= new ObjectInputStream(archivo);
           if(entrada!=null)
              clclientes=(ArrayList<Clientes>) entrada.readObject();
           
           entrada.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
    
     public void deserializarProductos()
    {
       FileInputStream archivo;
       ObjectInputStream entrada;
       try{
       
           archivo= new FileInputStream("productos.dat");
           entrada= new ObjectInputStream(archivo);
           if(entrada!=null)
              pdproductos=(ArrayList<Productos>) entrada.readObject();
           
           entrada.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
     
     public void deserializarUsuarios()
    {
       FileInputStream archivo;
       ObjectInputStream entrada;
       try{
       
           archivo= new FileInputStream("usuarios.dat");
           entrada= new ObjectInputStream(archivo);
           if(entrada!=null)
              lusu=(ArrayList<Usuario>) entrada.readObject();
           
           entrada.close();
           
       }catch(Exception e1)
       {
         System.out.println("Error "+ e1.getMessage());
       }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_Producto;
    private javax.swing.JButton C_Usuario;
    private javax.swing.JButton c_cliente;
    private javax.swing.JButton cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JButton producto;
    private javax.swing.JButton salir;
    private javax.swing.JButton usuario;
    private javax.swing.JButton venta;
    // End of variables declaration//GEN-END:variables
}
